# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be92798a84faed80fb71b5541a97b62da8104d3f6bbffa74b4c6c8e97caa3f3a6b7d3c057dd761cf2e6d7d3bf5c94dfbc492643193786b7671f8a8c8a2f9a13

test:
  secret_key_base: 5fe13e6b434c1a229ff8a6e4a4488e4f4b5a48b95b3e5f6971297c9b6230a21f59de7c949b535859e4befcbf332294fee247f88b1e9097610f6988b13e0c5f21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
